export const Types = {
  CARD_TOGGLE_CLICK: "CARD_TOGGLE_CLICK",
  CARD_COMPARE_COLORS: "CARD_COMPARE_COLORS",
  CARD_COMPARE_START: "CARD_COMPARE_START",
  CARD_COMPARE_FINISH: "CARD_COMPARE_FINISH"
};
