export const Types = {
  CARD_TOGGLE_CLICK: "CARD_TOGGLE_CLICK",
  CARD_CLICKED: "CARD_CLICKED",
  CARD_COMPARE_COLORS: "CARD_COMPARE_COLORS",
  CARD_COLORS_MATCH: "CARD_COLORS_MATCH",
  CARD_COLORS_NOT_MATCH: "CARD_COLORS_NOT_MATCH"
};
